### ISSUE TITLE
hugo server image relative path issue

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#10]
Current the markdown relative path doesn't work for the hugo server, it's quite difficult for us support markdown display and hugo server rendering at the same time.
Maybe we can find a way to support both senairons at same time.

**Comment by hanyouqing** [comment]
Try add `uglyurls = true` to `config.toml`. I've verified, it works for me(both preview image in MD file and Hugo server).

**Comment by WillemJiang** [comment]
@hanyouqing  Thanks, let me try it.
