### ISSUE TITLE
[约稿]开源心路历程

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#118]
ALC Bejing 的志愿者 王福政 最近写了一篇blog  https://quakewang.github.io/life/coscon/ 介绍他接触开源的心路历程。

**Comment by WillemJiang** [comment]
@QuakeWang 在发布微信的时候可以把之前的照片加上 ：）

**Comment by QuakeWang** [comment]
> @QuakeWang 在发布微信的时候可以把之前的照片加上 ：）

嗯嗯 好的：）

**Comment by QuakeWang** [comment]
公众号已发布。https://mp.weixin.qq.com/s/Pb6sjpJZRxLc7HJ0p2pifQ
