### ISSUE TITLE
Refine the script of a video

### ISSUE THREAD

**Issue by Jennifer88huang** [alc-beijing/alc-site#122]
The other day, when I watched a video shared in the ALC, and found that some scripts could be further improved. I copied the original text, and after I had time to improve it today, I could not find the original path for the script.
Here is the improved part for the scripts, and anyone knows the path can help on it.

1
00:00:00,030 --> 00:00:04,530
what we create runs everywhere
我们创造的东西遍布全球

2
00:00:04,730 --> 00:00:06,849
it's literally used everywhere in the world
从字面上说，全球各地都在使用

3
00:00:07,049 --> 00:00:08,919
today without the Apache，the internet
如果没有 Apache，

4
00:00:09,119 --> 00:00:10,180
that we know today would not have happened。
就没有人人在用的互联网

5
00:00:10,380 --> 00:00:12,669
the best database，the best streaming framework.
没有更好的数据库和流框架。

6
00:00:12,869 --> 00:00:14,349
We're creating industry's.
我们创建了一个新的产业。

7
00:00:14,548 --> 00:00:17,220
Programming for fun.
为乐趣而编程。

8
00:00:17,420 --> 00:00:20,409
People 

It's a great group of people.
这是一群很棒的人。

9
00:00:20,609 --> 00:00:22,419
It's connecting people. It's building bridges
它把人们联系在一起。 它架起了一座桥梁，

10
00:00:22,618 --> 00:00:25,030
people from China people from Europe.
把中国人与欧洲人联系在一起。

11
00:00:25,230 --> 00:00:26,940
It doesn't matter what language you speak
不管你说什么语言

12
00:00:27,140 --> 00:00:28,568
where you come from
来自何地

13
00:00:28,768 --> 00:00:31,120
Apache is really good at bringing people together 
Apache 都能把人们召集在一起

14
00:00:31,320 --> 00:00:33,159
and letting them work together
在一起工作

15
00:00:33,359 --> 00:00:35,709
without companies getting in the way.
不受公司的阻碍。

16
00:00:35,909 --> 00:00:37,779
Try to learn something from everybody every day.
每天我们都向别人学习新知识

17
00:00:37,979 --> 00:00:40,750
Inspiring， it makes me want to be better.
激励我们成为更好的自己。

18
00:00:40,950 --> 00:00:43,329
When working with people, 
和这些

19
00:00:43,530 --> 00:00:45,128
there are so much better than yourself 
比你更优秀的人一起工作，

20
00:00:45,329 --> 00:00:49,570
you learn a lot. Community，community in more community.
你学到很多东西。 社区，更多的社区组成一个大社区。

21
00:00:49,770 --> 00:00:51,489
People were so open and
大家都很开放

22
00:00:51,689 --> 00:00:55,059
so engaging and so excited to help.
很投入，非常愿意帮助他人。

23
00:00:55,259 --> 00:00:57,669
Don't be afraid to give, to share, you would get more out of it.
不要害怕给予、分享， 你能从中得到很多。

24
00:00:57,869 --> 00:00:59,799
I've got more out of Apache 
Apache 给予我的，远远超出

25
00:01:00,000 --> 00:01:02,169
than I've ever given.
我的付出。

26
00:01:02,369 --> 00:01:05,980
Building communities around people who are
这群人激情澎湃，

27
00:01:06,180 --> 00:01:09,000
passionate about solving problems.
喜欢解决各种问题，

28
00:01:09,200 --> 00:01:12,969
Create incredibly passionate communities who
构建一个激情四射的共同体，

29
00:01:13,170 --> 00:01:17,299
are then empowered to create incredibly powerful software.
然后依托这样的共同体，创建功能强大的软件

30
00:01:17,500 --> 00:01:19,058
The software that we've written
我们编写的软件

31
00:01:19,259 --> 00:01:21,069
how far it's gone and how
每天被全球各地的人们使用

32
00:01:21,269 --> 00:01:24,340
much it's used every day is staggering

33
00:01:24,540 --> 00:01:26,849
I'm proud to be a part of an
这个组织在改变世界，

34
00:01:27,049 --> 00:01:29,349
organization that has changed the world
能成为其中一员，我倍感自豪

35
00:01:29,549 --> 00:01:32,649
and I don't think many people understand
可能很多人还不了解

36
00:01:32,849 --> 00:01:35,659
exactly how Apache has changed the world.
Apache 如何改变了整个世界。

37
00:01:35,859 --> 00:01:37,579
It's impacted everyone when there's
它影响到每个人

38
00:01:37,780 --> 00:01:39,230
something now you know people can touch
包括你每天接触到的东西

39
00:01:39,430 --> 00:01:41,480
and interact with their phones and
和手机、汽车产生的关联，

40
00:01:41,680 --> 00:01:43,429
their car. And you know you realize all
当你会意识到

41
00:01:43,629 --> 00:01:45,739
of them are open-source software and it's like
这些都是开源软件时， 你会感叹

42
00:01:45,939 --> 00:01:48,049
wow okay this is something that's truly
开源软件真的在

43
00:01:48,250 --> 00:01:49,039
changed the world.
改变着世界。

44
00:01:49,239 --> 00:01:52,009
You know it's more than just technology
这不仅仅是技术，

45
00:01:52,209 --> 00:01:54,679
it's more than just coding. It's bringing
不仅仅是编码

46
00:01:54,879 --> 00:01:58,730
new ideas new aspects there's so much
它还带来了新思想，带来了如此多的

47
00:01:58,930 --> 00:02:01,399
more we can do with the technology.
可以应用的技术，

48
00:02:01,599 --> 00:02:03,439
We already have that is something that's
我们已经拥有了那些

49
00:02:03,640 --> 00:02:04,399
that's amazing
令人惊叹的

50
00:02:04,599 --> 00:02:06,709
with the foundation. That is something
与基金会相关的,

51
00:02:06,909 --> 00:02:09,259
it's so exciting, and that is the thing
令人振奋的成就,

52
00:02:09,459 --> 00:02:11,420
that really sort of keeps me interested
这也是(基金会)一直吸引着我、

53
00:02:11,620 --> 00:02:13,100
in and I'm passionate about.
让我充满激情的地方。

54
00:02:13,300 --> 00:02:15,890
There's still so much work to do, so like
我有好多工作要做，

55
00:02:16,090 --> 00:02:19,340
I'm gonna be busy for a while I think
我会忙一阵子，

56
00:02:19,539 --> 00:02:21,580
doing this kind of work and and I hope
我想做这种工作， 

57
00:02:21,780 --> 00:02:25,500
many other people are too.
我希望其他人也是这样。

58
00:02:26,310 --> 00:02:31,390
The best software in the world I mean
世界上最好的软件，

59
00:02:31,590 --> 00:02:34,459
that's the ASF
就是 ASF。

**Comment by Jennifer88huang** [comment]
This can be further improved if time permits.

**Comment by WillemJiang** [comment]
@Jennifer88huang  Thanks for looking into this issue, you can find the source file here 
https://github.com/alc-beijing/translation/blob/master/subtitles/Trillions%20and%20Trillions%20Served%20-%20%20Why%20Apache.srt .  Please send a PR for it.

**Comment by WillemJiang** [comment]
@Jennifer88huang any update for it？

**Comment by Jennifer88huang** [comment]
@WillemJiang Thanks for your reminder, I'll send a PR this week.

**Comment by Jennifer88huang** [comment]
@WillemJiang send a PR in https://github.com/alc-beijing/translation/pull/34

**Comment by WillemJiang** [comment]
Thanks the contribution of @Jennifer88huang.
I just upload the polished subtitle to bilibili https://www.bilibili.com/video/BV1az4y1X7Eb/.
