### ISSUE TITLE
SkyWalking DevCon 2020 公众号发布

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#125]
会场报道已经新鲜出炉  https://alc-beijing.github.io/alc-site/post/event/what_do_we_see_at_the_apache_skywalking_2020_devcon_event/
需要麻烦公众号排版发布

**Comment by QuakeWang** [comment]
收到 这篇推送我来做吧！

**Comment by WillemJiang** [comment]
多谢 @QuakeWang 文章已经发布 https://mp.weixin.qq.com/s?__biz=MzI4ODI1NjI2NA==&mid=2247484530&idx=1&sn=0b0c4099427bb1ee2e416129923cd043&chksm=ebc07c15dcb7f503bb4365d03509086614eb64322aecde9c35fccc223bd08d2f56218c82cf93&token=353053687&lang=zh_CN#rd
