### ISSUE TITLE
[podcast][TLP]Episode #8 ECharts 核心成员访谈 

### ISSUE THREAD

**Issue by lijiangsheng1** [alc-beijing/alc-site#127]

**Comment by lijiangsheng1** [comment]
E-Chart 孵化晋级为TLP在即，借机和VP、PMC等成员进行一番回顾。并尝试对项目进行进一步对推广～

**Comment by tristaZero** [comment]
Hi guys,
Here are some questions FYI,

- Echarts项目为什么想进入Apache孵化器？
- Echarts刚进入孵化器，社区状况如何？而现在呢？
- Echarts的孵化器时间，比一般项目时间长, 原因是什么?解决方案或经验总结？
- Echarts拥有庞大的用户群，如何看待这一情况？Pros and cons?
- Echarts未来的规划

**Comment by JesseZhou-1** [comment]
在娟姐的基础上补充两点问题：

* 1、 Echarts在适应Apache Way的过程中有遇到什么困难吗？比如在社区的交流上，或者在做决策过程中......如果有的话是如何解决的？
* 2、Echarts有做出那些努力来吸引以及激励贡献者吗？

**Comment by WillemJiang** [comment]
播客节目已完成。
