### ISSUE TITLE
ALC-Beijing 志愿者招募文章

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#13]
创建ALC-Beijing的目的， ALC-Beijing近期的工作目标，以及我们需要什么样的志愿者来帮忙。 
当然还要参加ALC-Beijing的活动有什么样的收获 。

**Comment by carp84** [comment]
@WillemJiang I'd like to help here, could you assign the issue to me? Thanks. :-)

**Comment by WillemJiang** [comment]
@carp84  Just assigned this issue to you.

**Comment by WillemJiang** [comment]
@carp84 Any update of this article?
Please let me know if you need any help from my side.

**Comment by carp84** [comment]
@WillemJiang Sorry for the lag, will submit a PR in one day or two.

**Comment by WillemJiang** [comment]
由于疫情影响，目前ALC Beijing主要是线上活动为主， 需要的帮助的内容有：
* [解决网站模板的问题](https://github.com/WillemJiang/alc-site/issues/16)
* [对ALC Beijing 成员进行采访宣传](https://github.com/WillemJiang/alc-site/issues/12)
* 公众号的编辑工作
后续的线下活动，需要更多志愿者的参与，这部分的内容@carp84可以帮忙列一下。

**Comment by WillemJiang** [comment]
Just reopen the issue as we need to publish the article into Wechat account.

**Comment by carp84** [comment]
Any additional action required? Just let me know if I could help @WillemJiang , thanks.

**Comment by WillemJiang** [comment]
文章已发布。
