### ISSUE TITLE
增加 alc-site 主题菜单栏选项

### ISSUE THREAD

**Issue by QuakeWang** [alc-beijing/alc-site#134]
根据现有项目增加 alc-site 网站的菜单栏，
[About](#)
[Posts](https://github.com/alc-beijing/alc-site/tree/master/content/post)
[Translation](https://github.com/alc-beijing/translation)

**Comment by WillemJiang** [comment]
@QuakeWang 挺好的， 可以提一个PR上来。 还有我们的网站都是中文的，可以把菜单换成中文的

**Comment by QuakeWang** [comment]
@WillemJiang 姜老师，关于定义菜单栏的分类，您有比较好的建议么？？

**Comment by WillemJiang** [comment]
多谢 @QuakeWang 
#135 已合并， 后续菜单栏分类参考#135 进行修改。
