### ISSUE TITLE
[约稿] CHOASS meetup 背后的故事

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#139]
认识小雅还是在去年年初的时候，我和她聊了一下她选的ServiceComb的实践项目，当时能感觉得到她参与开源的经验还很少；后续在CHOASS项目例会中发现她逐渐活跃起来，逐步在社区中找到自己的位置了；在刚刚结束的CHOASS 上海 Meetup，小雅忙前忙后俨然成为一个在CHOASS社区很相当活跃的老手的。

作为研二的学生，小雅已经有快一年多开源社区参与经验了，这次约稿的主要目的就是想探究一下小雅这一年是如何成长起来的？

**Comment by WillemJiang** [comment]
markdown的方式，提交可以参考这个文件 https://github.com/alc-beijing/alc-site/pull/138/files

**Comment by xiaoya-Esther** [comment]
我提交了PR #141，欢迎大家一起review我的社区之旅。

**Comment by kezhenxu94** [comment]
Cloed by #141
