### ISSUE TITLE
[短视频] 播客内容 点亮计划暑期2020优秀学生导师经验分享

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#142]
为了推广 ALC Beijing 播客内容， 我们需要出一期短视频来想大家推荐 暑期2020 优秀学生导师的实践经验。
具体任务如下
1. 从[播客文稿](https://alc-beijing.github.io/alc-site/post/podcast/episode-7-summer2020/) 以及 播客音频中提取几个同学和导师的金句。
2. 根据金句撰写脚本，把这些金句串起来。
3. 根据脚本将金句内容写的keynote幻灯上，然后配上音频输出 （必要时可以获取大家的照片），形成短片。

**Comment by WillemJiang** [comment]
> /Mark🙂

Welcome to join the community  :)

**Comment by zihanyu4** [comment]
文稿部分 初版
[金句改.docx](https://github.com/alc-beijing/alc-site/files/5807388/default.docx)
ppt版
[播客.pptx](https://github.com/alc-beijing/alc-site/files/5807390/default.pptx)

**Comment by WillemJiang** [comment]
赞， @zihanyu4 金句版本。
我们可以出三个小视频来把这部分的内容展示出来。
