### ISSUE TITLE
[podcast]Episode #9 开源社区的非代码贡献

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#143]
对于在校大学生来说，参与到开源项目有哪些困难, 如何克服这些困难? 开源项目中的非代码贡献有哪些？如何从非代码贡献做起，一步步融入到开源社区中来 ？
最近ALC Beijing 公众号刊发了 有关夏小雅[参与CHOASS项目并组织上海Meetup的文章](https://alc-beijing.github.io/alc-site/post/chaoss_meetup_sharing/)，在文章中我们可以看到通过非代码贡献也能获得社区的认可，并收获简单的快乐。

为此我们可以组织一次播客，采访一下夏小雅同学，周禹任，让他们介绍一下参与社区进行非代码贡献相关的心得和经验。

**Comment by WillemJiang** [comment]
@xiaoya-Esther @JesseZhou-1  咱们可以一起商量一个时间。

**Comment by xiaoya-Esther** [comment]
不知道周末是否方便？我这周末没问题的

**Comment by JesseZhou-1** [comment]
我这个周末也可以

**Comment by tristaZero** [comment]
Here are some questions for us,

1 CHAOSS及本次嘉宾介绍
2 为什么想申请Season of Docs，在其中主要做什么
3 在这过程中最大的感受、获得的经验
4 有关英语交流、交流的心态问题
5 为什么想举办CHAOSS Shanghai Meetup、难点
6 非代码贡献内容
7 给予的建议
8 未来规划

**Comment by WillemJiang** [comment]
要不我们还是约这周日晚上8点？

**Comment by WillemJiang** [comment]
我觉得问题的顺序可以调整和精简一下。

嘉宾介绍完之后，
在校大学生如何丰富自己的实习经历
可以问一下在校大学生参加开源项目的难点有哪些？
然后提一下开源社区非代码贡献是什么？
小雅在CHOASS 社区的经历
禹任 在Apache IoTDB 以及 ALC Beijing的翻译项目的经历

> Here are some questions for us,
> 
> 1 CHAOSS及本次嘉宾介绍
> 2 为什么想申请Season of Docs，在其中主要做什么
> 3 在这过程中最大的感受、获得的经验
> 4 有关英语交流、交流的心态问题
> 5 为什么想举办CHAOSS Shanghai Meetup、难点
> 6 非代码贡献内容
> 7 给予的建议
> 8 未来规划
> 
> 大家可以看下 修改。

**Comment by tristaZero** [comment]
> 嘉宾介绍完之后，
在校大学生如何丰富自己的实习经历
可以问一下在校大学生参加开源项目的难点有哪些？
然后提一下开源社区非代码贡献是什么？
小雅在CHOASS 社区的经历
禹任 在Apache IoTDB 以及 ALC Beijing的翻译项目的经历

赞

**Comment by tristaZero** [comment]
> 要不我们还是约这周日晚上8点

我可以的

**Comment by xiaoya-Esther** [comment]
> 要不我们还是约这周日晚上8点？

没问题

**Comment by lijiangsheng1** [comment]
Zoom Meeting is ready! Have fun!

Topic: ALC Beijing Podcast : contributing community without coding 
Time: Jan 24, 2021 08:00 PM Beijing, Shanghai

Join Zoom Meeting
https://zoom.com.cn/j/63039198355?pwd=VFlXcXNoei9BRjl0bjVsUnpLTmNFQT09

**Comment by JesseZhou-1** [comment]
好的，没问题

**Comment by WillemJiang** [comment]
本期podcast已经发布。
