### ISSUE TITLE
[podcast] 内源之路

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#153]
内源的播客是ALC Beijing访问量最大的播客， 距离上次的录制已经过去了半年多的时间了。 
这次播客的主题是分析大家在实施内源过程中的心得：

1. 内源的适用场景有哪些， 什么样的项目适合内源？
2. 内源项目的维护主体是谁，谁为内源项目的商业交付负责？ 
3. 大家参与内源的原动力是什么？
4. 如何在内源项目中实践Apache way？

**Comment by WillemJiang** [comment]
本次播客邀请到的嘉宾： 谭中意, 周禹任
主持人： 潘娟，姜宁

**Comment by membphis** [comment]
关于内源（内部开源）的讨论，我看过的资料很少。
想问下，内源是否只适合大公司？

**Comment by WillemJiang** [comment]
> 关于内源（内部开源）的讨论，我看过的资料很少。
> 想问下，内源是否只适合大公司？

小公司应该更好转型，招一群做开源的人就可以了：）
对于做开源的公司，就不需要走内源这条路了。

**Comment by WillemJiang** [comment]
喜马拉雅已经发布， https://www.ximalaya.com/keji/37853515/418249939
