### ISSUE TITLE
【社区活动】是否考虑做一系列开源项目进企业的系列活动？

### ISSUE THREAD

**Issue by francis-du** [alc-beijing/alc-site#157]
1. 很多企业都有在用 ASF 项目，每个公司内部也有相关的分享，可以让开源项目 Leader / PMC Member / Commiter / Contributer 参与进来，在不同的企业举办相对应的一些社区活动。

2.  大部分企业都对开源项目比较友好，能够提供免费的场地，这块通过做系列活动是否能积累一些资源，用于各个开源项目的线下活动来举办活动。

3. 有些企业有自己内部的学习平台 / 公开课之类的，是否可以联合这方面的资源做一些公开课，社区有核心技术人员，公司有好的落地场景，课程质量十分有保障。

4. 以上这些都有助于提高项目曝光度，也能够为各个公司解决一部分项目的使用问题，甚至作为该项目社区 Leader 能够为企业提供一些咨询方面的支持。

**Comment by jixuan1989** [comment]
+1.

可以考虑ALC Beijing Meetup?

Francis Du ***@***.***> 于2021年7月21日周三 下午11:13写道：

**Comment by WillemJiang** [comment]
这个提议很好，最近刚刚把ApacheCon Asia的事情忙完，我觉得可以好好来策划一下这个活动了。 
大家有什么想法都可以在issue里讨论起来， 争取在9月9日的例会里面能形成一个提案供大家讨论。 

我觉得做这件事情的就是围绕着众多的Apache项目，帮助大家建立一个个垂直领域的CoP 知识共同体。
User Group可能是一个比较简单有效的组织形式，具体咱们可以先在企业内部从帮助大家对接Apache项目的开发者和使用者开始。 这个可能需要发动大家多做做宣传， 聚集人气。
