### ISSUE TITLE
[Podcast] 如何打造开放式组织

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#161]
红帽前CEO Jim 提出的[《开放式组织》](https://book.douban.com/subject/26894636/)理念是基于对开源社区及红帽 20 多年组织成功发展运作的经验总结及升华。

随着越来越多的企业开始拥抱开源，开始投入大量的人力物力参与到开源协作中， 传统的开发模式与开放式的协作模式产生了很大的冲突。 这次播客就是想和大家探讨一下开放式组织的理念是什么， 开放式组织是否能够帮助传统企业拥抱开放文化，打破传统的层级，摒弃自上而下、命令式与控制式管理方式，增强员工的参与、提高大家的目标感和热情度；为员工提供适宜的、可以孵化创新的土壤。

这次播客可以结合书中的内容和大家聊聊开放式组织的话题：（欢迎大家反馈话题）
1. 什么是开放式的组织？
2. 开放式组织与传统组织有什么不同？
3. 如何点燃大家的工作热情？
4. 如何提升员工的参与度？

参考资料：
[红帽中国区总裁曹衡康：如何打造开放式组织 ?](https://www.infoq.cn/article/npkme-vrgarlrm6hviiz)
[Two Hats of Developers](https://mp.weixin.qq.com/s/iBIpgidSt1a78M4V4_7GzQ)

**Comment by tisonkun** [comment]
### 为什么要理解开放式组织这种形式？

开源软件在开源协同的生产力加持下，在不同领域攻城略地，击溃了专有软件的统治。企业基于软件打造商业价值，需要了解开源软件，甚至就基于开源软件打造商业价值。在这种情况下，传统的控制管理模型会导致企业和开源社区激烈的摩擦。要想获得生产力的提升，企业必须成为开放式组织。

本书并没有过多的讲这部分内容，因为红帽已经走过了这个阶段。要想跟 Linux 社区最好的协同，乃至形成某种意义上的“原厂”品牌，必须以开放式组织的形式运作。本书更多的是讲在已经要运行一个开放式组织的前提下，如何发挥这一组织形式最大的生产力。

**Comment by tisonkun** [comment]
### 点燃工作热情

不是从无到有。原章节名即《构建充满热情的工作环境》，重点在环境。一个人没有热情，是很难点燃出热情的，根本就不可燃。能做的是环境压抑了人原本的热情，破除环境当中的限制条件，释放原本就存在的工作热情。

### 提升员工的参与度

首先自己要参与，而不是作为一个局外人去“提升其他员工的参与度”。对于参与的讨论，在《企业的人性面》当中花了第九章一整张讨论。根本是要树立诚信，员工能够真正的参与到事务活动和决策中来，整个旅程没有破坏安全感和信任的坏例子。

假模假样的号召参与，实际并不采纳意见等仍然遵循控制管理模型的做法，并不能够满天过海，反而是失掉员工的信任，进而整个提高参与度的努力都会失败。

**Comment by tisonkun** [comment]
### 开放式组织是不是未来唯一的或者最高级的组织形式？

不是，它是一种选择。控制管理模型也有适合它的军队和教会等组织，上面已经讲过了理解和采取开放式组织的原因。现在仍然有专有软件统治某个领域，仍然有源代码公开的专有软件开放 API 或带有限制的修改，如果你的商业模式适用于这些形式，大可不必采用开放式组织的理论。

但是，软件复杂度将不断提高，基础软件乃至其分支再也无法仅凭一个人或一个公司雇佣一群人来编写，开源社区这种跨越组织边界，凝聚不同背景专家共同开发的形式，将会以生产更高质量的软件为标志成为事实标准。所以至少这个领域的组织，应当理解和采取开放式组织的形式。这种形式也是当前开源社区唯一成功的组织形式。

**Comment by WillemJiang** [comment]
@tisonkun 已经提前透露聊天议题了。 
我觉得还有一些引申内容例如：

- 开放式组织企业文化的形成环境
- 企业管理的Y理论假设 
- Remote 和控制与信任之间的关系

**Comment by WillemJiang** [comment]
节目录制已完成
https://www.ximalaya.com/sound/497066284
