### ISSUE TITLE
[Podcast] 聊聊Apache SkyWalking 2021 的contributor 增长的背后

### ISSUE THREAD

**Issue by lijiangsheng1** [alc-beijing/alc-site#163]
![image](https://user-images.githubusercontent.com/1545933/146676433-43ae291d-7f39-4051-b3e0-9e8f2d069b74.png)

透过表象看本质。

我们打算从云计算的发展、开源的崛起、数字化转型、开发者的启蒙等诸多角度挖掘一下这个开源项目的contritutor 增长背后的底层逻辑。

**Comment by JesseZhou-1** [comment]
如果可以的话，是否也可以从社区核心维护团队的所做的一些努力和工作出发，去探索社区贡献者增长的原因？

**Comment by WillemJiang** [comment]
开源项目发展， 一般都要经历从0到1， 然后从1到n的发展阶段。 
1. 在这几个阶段中团队核心是如何逐步壮大起来？
2. 在每个阶段投入的重点又是什么？
3. 回顾这几个阶段，有哪些工作是做得比较好的， 有哪些工作是还需要改进的。

**Comment by lijiangsheng1** [comment]
done.
