### ISSUE TITLE
[Podcast] 开源交流的自信心话题

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#166]
CHAOSS China 最近有一个讨论

> 描述了中国开发者参与国际社区遇到的一些问题，例如要面子，在公共场合自我展现缺乏信心，错失很多机会。 
> 
> 中国老话，人要脸，树要皮。。。 哈哈哈 根生蒂固
> 
> 我有点想找个机会跟大家交流一下这个话题，根据回国一段时间看到的情况，我觉得交流上有自信问题，有文化问题，有语言问题，有社区感问题，维度是多面的。
> 
> 有一个观察是国内见到的很多人非常的两极化，用开车来比喻，就是路上只有两种人，比自己开的慢的菜鸟和比自己开的快的sb
> 
> 东亚三国的文化拥有的一个共性就是一种“别扭”

**Comment by eyehwan** [comment]
1. 可以讲一下在社区与老外沟通的技巧。
2. 善用工具，比如zoom的线上直译功能。
3. 如何建立信心的例子，很宝贵，值得分享。

**Comment by LinuxSuRen** [comment]
播客嘉宾不可能有太多，但可以考虑把其他人的核心观点剪辑进去。例如：在开始或者某个未知上，加上“众家”的观点，也算是一种对多样性支持的体验。不过，实际操作上会稍微复杂些。

另外，缺乏自信的一个潜在原因可能会有：
* 过度在意别人对自己的看法
* 过度在意别人的看法
* 担心出错，担心xxx
  * 在容错性差的环境里，就只能谨言慎行了

**Comment by WillemJiang** [comment]
我这边可以贡献一些公开演讲和竞选声明相关的一些案例。

**Comment by WillemJiang** [comment]
最近的ALC Beijing 播客 有一个Talk is not cheap的讨论，目的是要鼓励程序员对外交流。
https://www.ximalaya.com/sound/583205323

回看这个话题， 感觉我们可以提供更多帮助程序员提升交流自信心的建议，欢迎大家持续发表评论补充素材。

**Comment by alili** [comment]
语言是一个问题，首先就是英语的能力。可能看文章还可以，但是一旦需要即时交流就很不擅长。

英语世界也有一些流行的黑话，比如TL;DR，LGTM，让新人进入成本变高。

[国人其实也不是都很内向](https://github.com/komeiji-satori/Dress)，还是需要一个合适的契机去参与。

因为海外环境比较陌生，而且你不是生活在这个环境中，所以很难获得来自环境的反馈，用来对自己进行修正。

类比一下，其实很多程序员写代码的时候也没人review，这也导致了很多程序员的自我评价是有问题的，我们都很清楚自己是不是擅长骑车，了解NBA，掌握游泳，但是在简历中写自己编程技能的时候，这些程序副词却用不好。

原因就是缺少来自环境的反馈，所以不好确认自己的能力水平。

我觉得破局的点在于要接触真正的国外开发者，以及参与到海外社区。比如ALC可以组织海外项目对中国学生或者开发者的交流，提供一些[good first issue]((https://goodfirstissue.dev/language/javascript)。

对于很多人来说，参与海外社区交流的难度，其实和参与社区交流的难度差不多，只是缺少了一个初始的机会。

**Comment by alili** [comment]
https://www.zhihu.com/question/30214063/answer/2734372017

> 大体上来说，用马克思的概念来说的话就是东亚文化最显著的特点就是你不是你自己，你只是你的社会关系。
>
> 西方文化是鼓励你做你自己，你先身为自由的独立个体，再按照自己的思想去构建社会关系，建立社会契约。只不过在建立社会关系后，需要尽到这份社会契约的义务而已。所以虽然西方文化中也很看中社会关系,但是依旧承认除了社会关系外,你自己这个个体的独立存在的.

https://github.com/shimohq/chinese-programmer-wrong-pronunciation
另一个想法是，开篇可以聊聊程序员英语的问题，包括单词读音，用英语写commit，以及写文档的问题。
这些确实是交流的障碍。

**Comment by alili** [comment]
## 引子
交流的基础是语言，很多程序员面临语言问题，不是编程语言，是自然语言。
本来英语就不好，而且你发现开源社区还有很多黑话。
我们先聊聊常读错的单词，以及黑话。

## 没有自信也要入门
我们在一开始可能遇到很多障碍，可能非常影响自信心的建立，甚至无法入门
大家在进入开源社区的初期也是没自信的么？遇到了什么挫折？

## 自信 = 不要脸 ？
印度英语不标准，但是他们很自信，我不尴尬，尴尬的就是别人。
也有一些同学一开始就很自信，很多技术社区写文章的都是年轻人，初生牛犊不怕糊。
盲目的勇敢其实不是自信。

## 技术好 = 自信？
是不是工作时间长了，技术好了，就自信了？
我们身边有一些过于自信的人。
技术好是自信的必要条件吗？

## 如何获得自信
通过反馈和环境自我确认
主动的做成事情，Get your hands dirty
good first issue
对新人友好的mentor文化

## 文化自信与客随主便
为什么这个项目都是中国人，却要说英语
说母语是文化自信吗？
其他小语种项目有遇到类似问题么？

## 自信和开源
自信是参与开源的必要条件？
开放更有利于自我认知。
参与开源会让你更自信吗？

**Comment by WillemJiang** [comment]
在@alili的基础上添加了一些内容。准备11月19日正式录制。

**Comment by WillemJiang** [comment]
播客已发布： https://www.ximalaya.com/sound/594133834
