### ISSUE TITLE
[发版] Apache 孵化项目发版常见问题及注意事项

### ISSUE THREAD

**Issue by imbajin** [alc-beijing/alc-site#173]
相信对于每个初入 ASF 的项目来说, **第一次**发版都会多少遇到不少小问题和麻烦事, 尤其以 `License/Notice/Copyright` 相关的问题为典型代表, 主要原因思考了下可能有以下:
- ASF 官方的文档颇为零散, 社区的普通开发者和未参与发版的经常没有耐心通读所有文档以及注意到**关键**事项 (或理解有偏差)
- ASF 官方文档对于有些描述仍较为**模糊**, 或者它直接建议 PMC/Mentor/Mail 来讨论决策, 但这部分结论通常没有更新记录到文档中
- ASF 官方没有给大家推荐类似 `skywalking-eye`  (header/dependency) 的自动化检查, 这些对初次发版的同学可能会有许多帮助
- 中/英语言/语义上的理解偏差, 从而误解了某些内容

借着 `HugeGraph` 这次发版的机会, 我也顺便总结了一些PR/邮件中遇到的事项和经验, 暂时放在 [HugeGraph-Wiki](https://github.com/apache/incubator-hugegraph/wiki/Apache%E5%8F%91%E7%89%88%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9) 页面中, 之后大家觉得有需要/帮助可以考虑放在 ALC-BeiJing 的**官网文章 / Wiki** 中.

**PS**: 上面的文档还处于**更新**状态, 可能存在不严谨的地方, 欢迎大家一起来 review 和补充内容 (可以直接在这个 issue 里对存疑点进行补充)

**Comment by WillemJiang** [comment]
@imbajin 整理的挺好的， 建议把ASF网站上的指导链接加上，方便大家进一步参考。 

后续我们可以把材料以Blog的方式整合到 ALC Beijing 网站上。 相信可以帮助到更多ASF项目发版的小伙伴。

**Comment by imbajin** [comment]
> @imbajin 整理的挺好的， 建议把ASF网站上的指导链接加上，方便大家进一步参考。 
> 
> 后续我们可以把材料以Blog的方式整合到 ALC Beijing 网站上。 相信可以帮助到更多ASF项目发版的小伙伴。 

👌，refer 之后完善补充下，包括会加入一下自动化检查工具的引用

文档里还有一些待确定的点（或者我推测的不一定理解正确），之后也可以提doc-pr的时候review一一确认一下，感谢

**Comment by WillemJiang** [comment]
@imbajin 不知道文档准备如何了， 可以考虑提一个PR， 后续可以帮到更多孵化中的项目。

**Comment by imbajin** [comment]
> @imbajin 不知道文档准备如何了， 可以考虑提一个PR， 后续可以帮到更多孵化中的项目。 
> 

可以的，提到什么地方（repo/path）合适点~

**Comment by WillemJiang** [comment]
可以参考其他文件的格式把文章发到 https://github.com/alc-beijing/alc-site/tree/master/content/post。
这样文章就可以出现在 ALC Beijing GitHub pages [alc-beijing.github.io/alc-site/](https://alc-beijing.github.io/alc-site/)
