### ISSUE TITLE
[翻译校对] Apache Project Maturity Model (Apache 项目成熟度模型)

### ISSUE THREAD

**Issue by tedliu1** [alc-beijing/alc-site#183]
原文链接：https://community.apache.org/apache-way/apache-project-maturity-model.html
协同编辑：https://hackmd.io/@tedliu1/BJkfNg5Xp/edit

**Comment by tedliu1** [comment]
@WillemJiang 原文介绍部分已加上，并改为 Markdown 格式，可以在线协同编辑：https://hackmd.io/@tedliu1/BJkfNg5Xp/edit

**Comment by WillemJiang** [comment]
校对后的翻译内容可以ALC Beijing的博客网站上。

**Comment by tedliu1** [comment]
@WillemJiang 此篇已经发布到 ALC Beijing 微信公众号以及博客，此 issue 可以 close 了，对吗？
