### ISSUE TITLE
[Translation] 新孵化项目提案

### ISSUE THREAD

**Issue by tedliu1** [alc-beijing/alc-site#185]
原文：https://cwiki.apache.org/confluence/display/INCUBATOR/New+Podling+Proposal?desktop=true&macroName=markdown
翻译：https://hackmd.io/@tedliu1/Bkm5nKhmT/edit
微信公众号：https://mp.weixin.qq.com/s/2L5HSDxx2JkohjrYfkpiwQ

**Comment by tedliu1** [comment]
已将飞书文档内容改为 Markdown 格式，并可以协同编辑：https://hackmd.io/@tedliu1/Bkm5nKhmT/edit

**Comment by WillemJiang** [comment]
文档已提交 https://alc-beijing.github.io/alc-site/post/apache-way/new-proposal-template-guide/
