### ISSUE TITLE
[翻译校对] 孵化器领路人的职责

### ISSUE THREAD

**Issue by tedliu1** [alc-beijing/alc-site#186]
孵化器领路人的职责
原文：https://incubator.apache.org/guides/roles_and_responsibilities.html#champion
翻译：https://hackmd.io/@tedliu1/BJptmDA7p/edit

**Comment by WillemJiang** [comment]
@tedliu1 参考原文结合实践整理了相关的领路人还有导师的职责， 还烦请指正。 
https://alc-beijing.github.io/alc-site/post/apache-way/incubator-champion-mentor-responsibility/

**Comment by tedliu1** [comment]
@WillemJiang 看到你的评论了，也看到你整合到 ALC Beijing 的博客里了。我觉得很赞。此 issue 应该可以 close 了，对吗？
