### ISSUE TITLE
[翻译校对] 孵化器导师的职责

### ISSUE THREAD

**Issue by tedliu1** [alc-beijing/alc-site#187]
孵化器导师的职责
原文：https://incubator.apache.org/guides/roles_and_responsibilities.html#mentor
翻译：https://hackmd.io/@tedliu1/SkCojwCm6/edit

**Comment by WillemJiang** [comment]
@tedliu1 校对意见已反馈。

**Comment by tedliu1** [comment]
@WillemJiang 看到你的评论了，也看到你整合到 ALC Beijing 的博客里了。此 issue 应该可以 close 了，对吗？
