### ISSUE TITLE
Set up a workflow to publish the source files as a web site

### ISSUE THREAD

**Issue by kezhenxu94** [alc-beijing/alc-site#25]

**Comment by WillemJiang** [comment]
@kezhenxu94 Could you add a quick summary about the this workflow?
 I cannot find the website from alc-beijing.github.io.

**Comment by kezhenxu94** [comment]
This workflow builds and uploads the generated html files into the branch [gh-pages](https://github.com/alc-beijing/alc-site/tree/gh-pages) in this repo, which automatically serves as the web site, we don't need to care about `alc-beijing.github.io` any more, and it should be deleted now

**Comment by WillemJiang** [comment]
How can we access the website?

**Comment by kezhenxu94** [comment]
> Thx for the information, just a quick question. 
> 
> How can we access the website?
> 
> 


https://alc-beijing.github.io/alc-site/
