### ISSUE TITLE
【成员采访】李橙子，用青春书写开源的故事

### ISSUE THREAD

**Issue by lijiangsheng1** [alc-beijing/alc-site#26]
策划人：@lijiangsheng1 
采访对象：李橙子

**Comment by lgcareer** [comment]
# 大纲

## 自我介绍

## 话题1：自己是如何进入到开源领域

## 话题2：自己对开源的理解

### 开源天然的优势

### open 开放性的讨论


## 话题3：Apache way介绍以及个人理解

## 话题4：开源之路带给我的成长


## 话题5：给以期望加入到开源领域的伙伴一些分享和建议

**Comment by lgcareer** [comment]
这是我准备的初步的几个话题，如果有需要修改和调整的可以一起讨论修改下

**Comment by WillemJiang** [comment]
播客已发布。
