### ISSUE TITLE
【Podcast】Episode #0 Say “hello，world” 

### ISSUE THREAD

**Issue by lijiangsheng1** [alc-beijing/alc-site#38]
播客，有其独特的魅力。
不知不觉，ALC Beijing podcast 已经录制了2期了，然而我们却忘记了第0期，
那就是介绍播客本身：
0、 播客的传播意义
1、 播客的受众群体
2、 ALC Beijing 会策划哪些内容？
3、ALC  Beijing  希望哪些嘉宾能够来聊？
4、对于Apache 文化，特别有意思的一点，就是代表个人，那么能不能做到在中国的环境中，不会以公司/企业/机构等单位了呢？

必须参加的有ALC Beijing 播客主持人： @WillemJiang @tristaZero @lijiangsheng1 

有强烈愿望想参与到播客活动中来的 ALC  Beijing 成员可报名并提供聊的内容。

其余情况，请回复本issue来进一步的说明情况。

**Comment by lijiangsheng1** [comment]
kickoff 的事情还是要做的。

**Comment by WillemJiang** [comment]
这个礼拜的team meeting可以明确一下。

**Comment by lijiangsheng1** [comment]
想起一个话题来：

多个主持人，一个嘉宾是不是效果会更好点？ 某些大咖可以考虑如此来做。

![image](https://user-images.githubusercontent.com/1545933/86525488-5a83c100-beba-11ea-8955-3b07f5527c55.png)

**Comment by WillemJiang** [comment]
时间是11号， 这周看看还能请到哪位大牛！

**Comment by tristaZero** [comment]
Sound interesting! 😉

**Comment by lijiangsheng1** [comment]
所有人都希望被记录！

没有被述说的就等于没有存在过。

**Comment by WillemJiang** [comment]
11号晚上已经录音， 后期制作还在进行中。

**Comment by lijiangsheng1** [comment]
https://alc-beijing.github.io/alc-site/post/podcast/episode-0-introduce-alc-beijing-podcast/

close this issue!
