### ISSUE TITLE
【Podcast】 Episode #5 ： 技术架构、Community和康威定律

### ISSUE THREAD

**Issue by lijiangsheng1** [alc-beijing/alc-site#39]
软件以其飞速的发展，经过60年的发展，再也没有一个人能够写出来可以使用的软件了，尤其是以自由/开源软件项目的壮大为证，更是让人的协作提上了前所未有的高度。
这也就是说，作为软件的设计者，或者说开源的软件设计者，开始的时候应不应该考虑人与人之间的协作？甚至是以全球视野的想象力来介入，即跨时区的异步沟通为切入点？
那么我们不妨以Apache 软件基金会下众多的项目为例，甚至是以更广泛的开源项目为例，如Linux、Kubernetes等，探讨下关于康威定律是否适用？ 架构和开源共同体（Community）究竟有没有关系？如果有的话，二者该如何理解？关系又该如何处理？

邀请嘉宾： 张亮@shardingsphere. 

所有对上述话题感兴趣的自由/开源相关人等均可报名。

**Comment by terrymanu** [comment]
非常高兴参与这么有意思的话题

**Comment by lijiangsheng1** [comment]
时间可否预定到6月14日周六晚？

再邀请一到两位嘉宾？

**Comment by lijiangsheng1** [comment]
在Mozilla 发布的OpenSource ArchType 的报告中，对技术架构和组织架构做了如下总结：

Does technical architecture match social structure?

* Technical architecture can have effects on governance, licensing, and overall project/community ecosystem.
* Is the project module-based with APIs, or is it a microservice architecture?
* Does the project involve a run-time extension language?
* Will the project encourage a semi-independent plugin ecosystem?
* Do the project’s choice of programming language(s) and dependencies match the intended archetype?
* Are the project’s collaboration tools and processes configured to match the intended archetype?

**Comment by rootsongjc** [comment]
开源社区的组织方式，这个话题挺有意思，到时候学习下。

**Comment by WillemJiang** [comment]
技术架构和组织结构的关系，上次ShardingSphere的访谈里面就提到这个话题， 最近 @terrymanu 在修改elasticJob项目代码的时候对软件架构进行了相关的改动，这些架构上的变化和开源项目的组织关系是有很大的关系， 幕后的故事可以跟大家聊一下哈。

**Comment by WillemJiang** [comment]
咱们是不是先把Podcast的录制时间订一下。

**Comment by lijiangsheng1** [comment]
先得邀请到人，然后再定时间。

**Comment by lijiangsheng1** [comment]
https://en.wikipedia.org/wiki/Conway%27s_law

**Comment by tristaZero** [comment]
开始造作了? 😏

**Comment by rootsongjc** [comment]
什么时间呢？

**Comment by WillemJiang** [comment]
@lijiangsheng1 @terrymanu @tristaZero 可以约一下时间了。

**Comment by WillemJiang** [comment]
已经录制完成了，现在制作中。

**Comment by WillemJiang** [comment]
> at what time do we start the topic
如果想围观，下次可以提前预约一下。

**Comment by WillemJiang** [comment]
@lijiangsheng1 咱们的文字稿需要出一下，这样好在公众号上面推一下。

**Comment by tristaZero** [comment]
Look forward to online!

**Comment by WillemJiang** [comment]
公众号已发布。
