### ISSUE TITLE
Create short code support of Ximalaya

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#40]
Ximalaya provides an iframe to host the podcast like this
```
<iframe height="230" width="260" src="https://www.ximalaya.com/thirdparty/player/sound/player.html?id=294907345&type=red" frameborder=0 allowfullscreen></iframe>
```
Hugo supports the iframe with [short code](https://gohugo.io/content-management/shortcodes/), here is [an example of youtube support](https://gohugo.io/templates/shortcode-templates/#single-positional-example-youtube).

We need to create a short code template  for Ximalaya template.

**Comment by hanyouqing** [comment]
Done: 
https://github.com/alc-beijing/alc-site/pull/43

**Comment by WillemJiang** [comment]
Thx @hanyouqing,  the short code for Ximalaya works great.
