### ISSUE TITLE
转发公众文章 步进式解读Apache许可证 

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#42]
公众文章链接 https://mp.weixin.qq.com/s/y6rysKAifxefqfhSzcQcHg
TODO 需要添加一个转发的前言

同时编辑文章

**Comment by sunshinemingo** [comment]
这篇我来吧

**Comment by WillemJiang** [comment]
👍。

**Comment by WillemJiang** [comment]
@sunshinemingo  导读内容如下 

> 无规矩不成方圆， 开源许可协议是开源世界运行的基石。 深入理解开源许可协议权利与义务不但可以帮助我们有效避免开源软件使用合规的问题，同时也可以帮助我们维护自己开源项目的合法权益。 卫sir的这篇《步进式解读 Apache 许可证》结合具体案例为我们全方位解读了Apache许可协议。 这篇文章很值得想深度参与开源项目开发的朋友阅读。

**Comment by lijiangsheng1** [comment]
https://mp.weixin.qq.com/s/-JfuVWZRerI4uuYxlkKCAw 

文章已经发布。
