### ISSUE TITLE
[Podcast]Episode #3 Apache APISIX 的孵化器之旅

### ISSUE THREAD

**Issue by moonming** [alc-beijing/alc-site#44]
- Apache APISIX 是什么
- 为什么加入 Apache 孵化器
- 如何吸引和激活项目贡献者
- Apache APISIX 如何快速发布 Apache release
- 社区要如何帮助 Apache APISIX 的使用者

**Comment by lijiangsheng1** [comment]
这个准备的很棒👍，不过即兴的更精彩！ 非常期待。
我们约到7月份如何？

**Comment by moonming** [comment]
没问题。我也喜欢即兴发挥

适兕 <notifications@github.com> 于 2020年5月17日周日 下午8:45写道：

**Comment by WillemJiang** [comment]
正好APISIX这个月开源一周年，然后也很快就会从Apache孵化器毕业， 这个月约着录一期如何？

**Comment by moonming** [comment]
我时间 ok：）

Thanks,
Ming Wen
Twitter: _WenMing


Willem Jiang <notifications@github.com> 于2020年6月6日周六 下午10:19写道：

**Comment by lijiangsheng1** [comment]
> 正好APISIX这个月开源一周年，然后也很快就会从Apache孵化器毕业， 这个月约着录一期如何？

既然这样的话，约个时间把。按照惯例是周末的晚上，大家没有问题的话，可以约的时间有：14、21、和28号，挑一个吧。

**Comment by moonming** [comment]
14 号如何？趁热打铁：）

Thanks,
Ming Wen
Twitter: _WenMing


适兕 <notifications@github.com> 于2020年6月8日周一 下午12:00写道：

**Comment by lijiangsheng1** [comment]
快人快语，😁 ，那就十四号，@moonming 负责召集相关的核心人员。我去 APISIX developer 发一封邀请邮件。

稍后我安排一个Zoom 视频会议。

**Comment by moonming** [comment]
OK

适兕 <notifications@github.com> 于 2020年6月8日周一 下午10:52写道：

**Comment by WillemJiang** [comment]
#72 采访音频与文章已发布。
