### ISSUE TITLE
ALC  Beijing成员介绍系列之：娟神的成长之路

### ISSUE THREAD

**Issue by lijiangsheng1** [alc-beijing/alc-site#46]
@tristaZero 有一篇类自传的文章，正在撰写中。

值得广为传播。

**Comment by lijiangsheng1** [comment]
I think this issue can close now, the introduce article already public to site.

https://alc-beijing.github.io/alc-site/post/heros_journey_trista/

**Comment by tristaZero** [comment]
Hi @lijiangsheng1 , Your contribution made ALC Beijing become prosperous, very appreciated!
