### ISSUE TITLE
Skip the deploy part work for PR

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#49]
We don't want to deploy the website of the PR build, so we need to skip the deploy part if the branch is not master.

**Comment by WillemJiang** [comment]
Merged the PR into master branch.

**Comment by kezhenxu94** [comment]
The idea behind deploying the website of the PR is to preview the content without setting up Hugo and build locally for reviewers, if I remember correctly

**Comment by WillemJiang** [comment]
Yes, but now we could have some contributor which has no access right of repo to send PR for polish the website. The original deploy part could be failed as the deploy key is not validate.
