### ISSUE TITLE
ALC Beijing 视频录制邀请

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#56]
明确一下视频要求（从云原生社区获得的模板）
视频时长：每人总时长控制在一分钟左右， 2 分钟以内。
视频技术要求：1080P 30 帧，**横屏**录制，采用同期声（非后期配音，因此请找一个安静的环境录制）请保持拍摄设备水平静止，不要晃动，人像居于中间。
着装要求：不允许穿着带有明显品牌商或者厂商 logo 的衣服（开源社区的文化衫除外）.

**Comment by lijiangsheng1** [comment]
每位成员自行录制至少一分钟的介绍。
1. 个人简介
2. 为何加入ALC Beijing？目前在ALC  Beijing主要的工作
3.  期望ALC Beijing 成为什么？

大家觉得如何？

**Comment by WillemJiang** [comment]
+1.
这里有一个有关Apache基金会的记录小片的可以参考一下。 

Apache Everywhere: the first "short" from the "Trillions"
documentary filmed onsite at ApacheCon Las Vegas and Berlin this past
year https://youtu.be/nXtIti9jMFI

**Comment by lijiangsheng1** [comment]
这个视频非常赞！

**Comment by WillemJiang** [comment]
这个视频应该是在ApacheCon的时候找专业摄影师帮着拍的， 如果想拍摄效果好的话，还是需要找专业摄影师帮忙。

**Comment by rootsongjc** [comment]
> +1.
> 这里有一个有关Apache基金会的记录小片的可以参考一下。
> 
> Apache Everywhere: the first "short" from the "Trillions"
> documentary filmed onsite at ApacheCon Las Vegas and Berlin this past
> year https://youtu.be/nXtIti9jMFI

这个视频看起来不错啊 !

**Comment by lijiangsheng1** [comment]
@all 我自己先录了一份，大家可以参考下内容。

https://1drv.ms/v/s!Arg2k_5HJFrbgYI9aDocshq6JjdmBw?e=VQhBGd

**Comment by chenliang613** [comment]
Can i join ?  :)

**Comment by jixuan1989** [comment]
1. 端午节第一天之前每人出一版：视频+个人title；
2. 6.22日 @WillemJiang  提醒没搞定的同志们加速；
3. 制作视频时统一给每个人都加上 ALC Beijing Member (如果是的话);
4. 邀请其他人录制视频，做介绍和祝愿；
5. B站账号账号注册 @WillemJiang

**Comment by WillemJiang** [comment]
> 
> 
> 能否考虑录一个中文，有关ASF故事的视频，可以幽默诙谐一点。

欢迎 Apache Member 为ALC-Beijing录制 祝福视频， 格式为： 个人介绍 + 对ALC Beijing的祝福。

**Comment by WillemJiang** [comment]
建议大家使用手机或者电脑横屏录制720P分辨率以上画质的视频。

**Comment by tristaZero** [comment]
Hi, here is my video. It is for about 1 min.

复制这段内容后打开百度网盘手机App，操作更方便哦
链接：https://pan.baidu.com/s/1G2n2tDwHVLMu6lOuvdN0VQ 提取码：327H

**Comment by WillemJiang** [comment]
@tristaZero 你的视频是竖屏录制的，剪辑起来会比较麻烦，可否提供一个横屏版本。

**Comment by tristaZero** [comment]
@WillemJiang Got it, I will try to fix this issue by some of the editors first. If not work, I will consider making another new one.

**Comment by rootsongjc** [comment]
云原生社区也在做一个端午节祝福视频，一起搞下？https://github.com/cloudnativeto/community/issues/4

**Comment by lgcareer** [comment]
下面的是我昨天录制的视频，时间为2分半
链接：https://pan.baidu.com/s/1N1mL12oqxvO05E-tQ8_RwA 
提取码：vxdi

**Comment by WillemJiang** [comment]
> 云原生社区也在做一个端午节祝福视频，一起搞下？[cloudnativeto/community#4](https://github.com/cloudnativeto/community/issues/4)

这个建议很好啊，正好可以联合推广一下。

**Comment by tristaZero** [comment]
> > 云原生社区也在做一个端午节祝福视频，一起搞下？[cloudnativeto/community#4](https://github.com/cloudnativeto/community/issues/4)
> 
> 这个建议很好啊，正好可以联合推广一下。

放开他，让我来。

**Comment by tristaZero** [comment]
Hi @WillemJiang  A new one here.

复制这段内容后打开百度网盘手机App，操作更方便哦
链接：https://pan.baidu.com/s/1ehssgmB-YNDvQIf-7TDNPg 提取码：0n7p

**Comment by wu-sheng** [comment]
Added, 7 days for download.

链接: https://pan.baidu.com/s/1XvsjLkb_De7h9CHieXgMdg 提取码: 9uja

**Comment by sunjincheng121** [comment]
链接: https://pan.baidu.com/s/1kmLncVSVnQ3dcyJut0GFSw 提取码: 7iq8

**Comment by terrymanu** [comment]
My video:
链接:https://pan.baidu.com/s/1-2Y3mjO2_5454CnM6gnnEg  密码:3w2u

**Comment by lijiangsheng1** [comment]
李建盛一分钟 ALC Beijing 自我介绍：

https://pan.baidu.com/s/1amzEQIvSIttBQVt-PlEzPQ 提取码：9F2G

**Comment by carp84** [comment]
My video (valid for 7 days):
链接: https://pan.baidu.com/s/1V_V0-rhF4DzH_a_1O1tWSw 提取码: f7wn

**Comment by moonming** [comment]
My video (valid for 7 days):
链接:https://pan.baidu.com/s/1b0VY8_whX37XAWBwBkEBFA  密码:52rv

**Comment by chenliang613** [comment]
链接: https://pan.baidu.com/s/1agrAjto0ihHNf87K7StYMg  密码: lkbq

**Comment by lgcareer** [comment]
@WillemJiang 姜老师好，之前的时间超出了2分钟，下面是新录制的一个。
链接: https://pan.baidu.com/s/18Qdiput4CefXM5bqjBAMtw 提取码: 6yrx

**Comment by jixuan1989** [comment]
我的video (7天):
https://cloud.tsinghua.edu.cn/f/34deea3af63542e4b0b0/?dl=1

**Comment by WillemJiang** [comment]
视频已经上传至B站 https://www.bilibili.com/video/BV1iD4y1Q7bf
