### ISSUE TITLE
为Apache纪录片提供字幕翻译

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#62]
最近Apache发布了一个member的访谈纪录片["Trillions and Trillions Served" documentary feature on The Apache Software Foundation](https://www.youtube.com/watch?v=UvuyBz1qMCE)， 咱们可以考虑提供相关的字幕翻译。 

@wu-sheng 在B站上传一个[版本](https://www.bilibili.com/video/BV1Uz411i7MH)。

**Comment by wu-sheng** [comment]
官方提供的翻译 [captions_trillions.sbv.zip](https://github.com/alc-beijing/alc-site/files/4785130/captions_trillions.sbv.zip)

国内可投稿字幕版本，https://www.bilibili.com/video/BV1Uz411i7MH

**Comment by rudy2steiner** [comment]
I can do it, please assign to me if no body get started!

**Comment by WillemJiang** [comment]
@rudy2steiner  Thanks for the offering,  we will discuss the translation task on [ALC Beijing bi weekly meeting](https://cwiki.apache.org/confluence/display/COMDEV/ALC+Beijing+Team+meeting) today.  Please feel free to join us.

**Comment by rudy2steiner** [comment]
Ok

**Comment by WillemJiang** [comment]
@rudy2steiner 不知道你有没有做相关的任务评估， 可以介绍一下你的翻译计划吗？

**Comment by rudy2steiner** [comment]
感觉翻译有点慢，我找了另一个小伙伴合译，目前前24分钟已经完成完成。等后面部分（另一个人负责）完成，会找人校对，可以参考
https://shimo.im/docs/J8W98gCwrCGyy8pd 跟踪进度

**Comment by WillemJiang** [comment]
我大概校对了前面11 分钟的内容， 里面涉及到了Apache的命名， 以及Apache软件的使用场景。
附上我校对之后的版本， 大家可以从11分钟之后接力。
[20200630 Trillions and Trillions Served -  -  documentary feature on The Apache Software Foundation .srt.zip](https://github.com/alc-beijing/alc-site/files/4848544/20200630.Trillions.and.Trillions.Served.-.-.documentary.feature.on.The.Apache.Software.Foundation.srt.zip)

**Comment by tristaZero** [comment]
@WillemJiang 分工下吧？我可能周末有时间review完。

**Comment by WillemJiang** [comment]
大家直接在上面的srt修改，提交diff文件， 我后续一并合入。
diff文件通过diff命令生成   

> diff ModifiedFile SourceFile

目前我校对到1320 行， 整个字幕文件5341.  大概还剩余4000行。
按照昨天晚上会议分工情况如下
任务1： 1320 ~ 2650  @tristaZero 
任务2： 2650 ~ 3980 @jixuan1989
任务3： 3980 ~ 5340 @carp84

**Comment by carp84** [comment]
I've just done my part, please refer to the attached diff file.

[translation_adjustment_part3_liyu.diff.txt](https://github.com/alc-beijing/alc-site/files/4872998/translation_adjustment_part3_liyu.diff.txt)

**Comment by carp84** [comment]
Patch generated with `diff -u`

[translation_adjustment_part3_liyu.diff.v2.txt](https://github.com/alc-beijing/alc-site/files/4873076/translation_adjustment_part3_liyu.diff.v2.txt)

**Comment by tristaZero** [comment]
请直接覆盖1320-2650行。
[1320-2650-trista.txt](https://github.com/alc-beijing/alc-site/files/4874449/1320-2650-trista.txt)

**Comment by WillemJiang** [comment]
I just merged the patch together and put the script [here](https://github.com/alc-beijing/translation/blob/master/subtitles/Trillions%20and%20Trillions%20Served%20-%20%20-%20%20documentary%20feature%20on%20The%20Apache%20Software%20Foundation.srt)
@jixuan1989  You can create a PR in the translation repo for it. We can keep polish the subtitle there .

**Comment by carp84** [comment]
Hi guys, how are things going here? Thanks.

**Comment by wu-sheng** [comment]
I am doing final review live on bilibili. Once done, which should be in 1730 today, I will update the site.
