### ISSUE TITLE
[podcast]Apache Way 是否能用于当下最热门的 innersource?

### ISSUE THREAD

**Issue by lijiangsheng1** [alc-beijing/alc-site#85]
开源越来越重要，而且在不断的吞噬着企业的软件技术栈，有的研究机构甚至得出的结论是超过95%都是开源。

Upstream first 当然是当仁不让的优先哲学！ 那么还有一个问题，那么开源巨大的好处，从大公司内部如何看待了呢？

比如Apache Way 该如何引入到企业内部来？拆除部门壁垒。

**Comment by tristaZero** [comment]
谭中意老师接收邀约，再加上老朋友姜老师，我们可以再邀请一位老师。
目前：
嘉宾 谭老师 姜老师
主持 建盛老师 @tristaZero

**Comment by tristaZero** [comment]
1. 内源的起源，为什么内源会兴起？
2. 内源的价值和意义
3. 内源和开源的差异点
4. Apache way能否应用到内源发展中？如何应用？part or whole?

**Comment by WillemJiang** [comment]
谭中意老师刚提交了一篇有关Apache Way的解读的文章， https://alc-beijing.github.io/alc-site/post/what_is_the_apache_way/。 聊天之前大家可以参考一下。

**Comment by WillemJiang** [comment]
@tristaZero 
我觉得还可以再增加一个 内源的实施的难点是什么？

**Comment by lijiangsheng1** [comment]
上次和庄表伟见面，他说可以约～

**Comment by WillemJiang** [comment]
补充链接信息：
1.  姜宁的修复n年前的bug博客  https://willemjiang.github.io/opensource/2019/05/04/How-to-maintain-n-years-old-code.html
2.  谭中意的到底什么是Apache Way https://alc-beijing.github.io/alc-site/post/what_is_the_apache_way/

**Comment by WillemJiang** [comment]
播客已发布  https://www.ximalaya.com/keji/37853515/353516198
文章已发布  https://alc-beijing.github.io/alc-site/post/podcast/episode-5-inner-source/
