### ISSUE TITLE
翻译ApacheCon@Home 的指导

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#88]
为了让大家能够更好参会，需要翻译相关的会议指导（不需要翻译Notes for speakers）
https://apachecon.com/acah2020/guide.html

**Comment by yang-7777** [comment]
Hello, please assign it to me.

**Comment by yang-7777** [comment]
## 会议指导
### 前期准备
为了您在ApacheCon@Home可以得到最好的体验，我们为你准备了以下清单，这样参会者就可以提前准备。 请提前浏览以下的技术要求和参会前可以准备的事项，这样就不需要在会议的过程中进行任何准备了。
### 注册
请确认你已经在 [ApacheConf @Home at Hopin](https://hopin.to/events/apachecon-home) 注册，如果你在右上角看到一条消息写着“You‘re in” 说明注册成功，借此机会可以点击“Add to calendar”将会议时间加入到日历。

### 网络速度
请尝试接入到至少 5Mbit/s 下载速度和2Mbit/s 上传速度的网络。下载速度和上传速度越高越能够提供一个更好的体验，30Mbit/s 的下载速度和10Mbit/s 上传速度是最理想的。尝试限制其他可能占用网速的访问客户，比如：提前一天将软件更新完成，避免软件在会议中运行，暂停或停止所有大型下载项目，如果需要可以断开其他设备的网络连接。推荐用网线进行网络连接。可以用一个在线网站进行网络速度检查，搜索 [Internet speed test](https://duckduckgo.com/?q=internet+speed+test&ia=web)。

### 浏览器
Hopin [支持](https://support.hopin.to/en/articles/2559500-hopin-compatibility) [Google Chrome](https://www.google.com/chrome/) (推荐) 和 [Mozilla Firefox](https://www.mozilla.org/en-US/firefox/new/) (备选)，其他浏览器均不支持。请确认您的浏览器是最新版本，按照浏览器说明 [Chrome](https://support.google.com/chrome/answer/95414) 或 [Firefox](https://support.mozilla.org/en-US/kb/update-firefox-latest-release)进行操作。

注意，Safari 与 Chrome 用的是同一引擎，用Safari打开网页也显示成功。但是，我们还是推荐使用Chrome。

请减少打开的网页数量和关闭不必要的浏览器扩展工具。不要打开多个Hopin的网页，如果有这样的需求请只保留一个网页的声音，其余静音。

### 设备
请优先考虑使用台式电脑或者笔记本，如果你使用的是平板电脑和手机设备确保你使用的是Google Chrome 或 Mozilla Firefox。

### 文献资料
在Hopin 上浏览为 [参会者](https://support.hopin.to/en/collections/1945014-using-hopin-as-an-attendee) 和 [演讲者](https://support.hopin.to/en/collections/2208884-using-hopin-as-a-speaker) 编写的文档。

### 填写个人资料
填写你的 [Hopin个人资料](https://hopin.to/users/sign_in)，以帮助建立会议成员之间的交流并找到志趣相投的人。你的个人资料会被保护仅会共享你同意的信息。

### 选择会议
浏览 [track](https://apachecon.com/acah2020/tracks/) 页面，然后选择您感兴趣的会议。在每个会议旁边，您会找到日历（📅）图标，单击该图标将为您提供iCalendar（.ical）文件，您可以将其导入日历软件中。单击会话的日期和时间将带您到一个在线服务，可用于将会话时间转换为不同的时区。会话时间轴上方显示的时间反映了您当地时区的时间，因此请确保您的计算机为您所在的地区配置了正确的时区。

## 会议中
在会议中你可能遇到一些问题，我们整理了一些常见的问题和一些通用的建议去避免问题的出现。

### 声音和视频
为了在会议中有更好的声音和图像的体验这里列举了一些建议：

要最大化扬声器视频或演示视频，请双击该视频流，这将放大视频流的该部分。
使用耳机播放音频，这将有助于理解扬声器，并防止在网络连接过程中出现任何音频反馈。 
请注意提示您允许访问麦克风或摄像头的提示，一旦被拒绝，则需要明确允许访问。请查阅有关在[Firefox](https://support.mozilla.org/en-US/kb/how-manage-your-camera-and-microphone-permissions) 和 [Chrome](https://support.google.com/chrome/answer/2693767?co=GENIE.Platform%3DDesktop&hl=en) 中允许访问的文档。

**Comment by WillemJiang** [comment]
@yang-7777 
> Hello, please assign it to me.
很高兴能能接受这个任务， 我会尽快把这篇文章提交到我们网站上的。 

另外针对 ApacheConf @Home at Hopin 可否写一个注册的说明文档？

**Comment by yang-7777** [comment]
## 关于ApacheConf @Home at Hopin的注册说明
1. 点击注册链接 [ApacheConf @Home at Hopin](https://hopin.to/events/apachecon-home)

2. 选择一个ticket，点击下方蓝色按钮checkout。（官网标注：General Admission即注册为免费，但如果你愿意帮助和支持活动可以选择Donation Ticket进行捐款）
![ac1](https://user-images.githubusercontent.com/67564630/93177358-446d6900-f765-11ea-97bb-350b570ef394.png)

3. 此时页面会跳转到注册页，请填写您的名（First name），姓（Last name），邮箱地址（Email address）和设定一个密码（Pasword）。勾选下方的条款与隐私协议，点击蓝色按钮sign up即可。
![ac2](https://user-images.githubusercontent.com/67564630/93177994-33712780-f766-11ea-93b7-176589b3fda1.png)

以上是注册的所有步骤。
### 检查是否注册成功

看到页面上有“You‘re in!”的提示则注册成功
![ac3](https://user-images.githubusercontent.com/67564630/93178392-beeab880-f766-11ea-9d85-90946afe5048.png)

或在右上角的个人信息中找到Events，点击进入看到如下页面，同样意味着注册成功
![ac4](https://user-images.githubusercontent.com/67564630/93178399-c27e3f80-f766-11ea-9506-6bae91453089.png)

**Comment by WillemJiang** [comment]
@yang-7777 多谢， Hopin注册内容我会补充到参会指导中的。 
还有就是之前翻译的内容 speaker应该翻译成演讲者，而不是扬声器。

**Comment by yang-7777** [comment]
> @yang-7777 多谢， Hopin注册内容我会补充到参会指导中的。
> 还有就是之前翻译的内容 speaker应该翻译成演讲者，而不是扬声器。

辛苦您review，确实是演讲者我当时有一些理解上的错误很抱歉

**Comment by WillemJiang** [comment]
修改已合并。

**Comment by WillemJiang** [comment]
注册指导已合并  https://github.com/alc-beijing/alc-site/pull/93
