### ISSUE TITLE
[翻译]ApacheCon 2020 新闻稿

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#96]
原文发布在ASF 的官方博客上
The Apache® Software Foundation Welcomes its Global Community Online at ApacheCon@Home
https://blogs.apache.org/conferences/entry/the-apache-software-foundation-welcomes

**Comment by tuhaihe** [comment]
我来认领下翻译~

**Comment by tuhaihe** [comment]
翻译内容：https://docs.google.com/document/d/1lzUHt1mhx_EsB9Yf6sY-ZU4cdXb4vyfa83LggY2k6vo/edit?usp=sharing 

@WillemJiang @lijiangsheng1 诸位帮忙看下哈，可以直接评论要修改的地方。

**Comment by WillemJiang** [comment]
赞， 我大概看了一下， 翻译质量还不错。 可否把翻译后的文章提交一个PR，这样可以做一个公众号页面向大家宣传一下。

**Comment by tuhaihe** [comment]
好的，我稍后提交PR.

**Comment by tuhaihe** [comment]
PR已经提交：https://github.com/alc-beijing/alc-site/pull/98

**Comment by WillemJiang** [comment]
PR已合入。
