### ISSUE TITLE
刷新 apachecon-2020-mandarin-track 页面

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/alc-site#97]
文章中圆桌演讲人介绍 遗漏了潘娟的介绍， 需要补充上去。 
同时公众号上 https://mp.weixin.qq.com/s/haeZ5Nx7quNWLvqUu226tw 还添加了有关吴晟的主题演讲的内容，需要同步刷新一下。

**Comment by WillemJiang** [comment]
@tuhaihe 麻烦抽空刷新一下。

**Comment by tuhaihe** [comment]
已更新提交：https://github.com/alc-beijing/alc-site/pull/99 @WillemJiang PTAL

**Comment by WillemJiang** [comment]
Merged the change into master branch.
